version: "3.8"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse-custom
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - ./data:/data
    environment:
      SYNAPSE_SERVER_NAME: "${SERVER_NAME}"
      SYNAPSE_REPORT_STATS: "no"
    user: "991:991"
