version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 8008
      PROXY_AUTH_ADD: "false"

  server:
    image: matrixdotorg/synapse:v1.144.0
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/synapse:/data
    environment:
      SYNAPSE_SERVER_NAME: "silly.com"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"
